version: "3.8"

services:
  mariadb:
    container_name: mariadb
    build: ./requirements/mariadb
    image: mariadb
    secrets:
      - db_password
      - db_root_password
    environment:
      - WORDPRESS_DB_HOST=${WORDPRESS_DB_HOST}
      - WORDPRESS_DB_NAME=${WORDPRESS_DB_NAME}
      - WORDPRESS_DB_USER=${WORDPRESS_DB_USER}
      - WORDPRESS_ROOT_USER=${WORDPRESS_ROOT_USER}
      - DOMAIN_NAME=${DOMAIN_NAME}
      - WORDPRESS_DB_PASSWORD_FILE=${WORDPRESS_DB_PASSWORD_FILE}
      - MYSQL_ROOT_PASSWORD_FILE=${MYSQL_ROOT_PASSWORD_FILE}
    volumes:
      - mariadb_data:/var/lib/mysql
    networks:
      - inception
    restart: always

  wordpress:
    container_name: wordpress
    build: ./requirements/wordpress
    image: wordpress
    secrets:
      - db_password
      - db_root_password
    environment:
      WORDPRESS_DB_HOST: ${WORDPRESS_DB_HOST}
      WORDPRESS_DB_NAME: ${WORDPRESS_DB_NAME}
      WORDPRESS_DB_USER: ${WORDPRESS_DB_USER}
      WORDPRESS_ROOT_USER: ${WORDPRESS_ROOT_USER}
      DOMAIN_NAME: ${DOMAIN_NAME}
      WORDPRESS_DB_PASSWORD_FILE: ${WORDPRESS_DB_PASSWORD_FILE}
      MYSQL_ROOT_PASSWORD_FILE: ${MYSQL_ROOT_PASSWORD_FILE}
    volumes:
      - wordpress_data:/var/www/html
    networks:
      - inception
    depends_on:
      - mariadb
    restart: always

  nginx:
    container_name: nginx
    build: ./requirements/nginx
    image: nginx
    ports:
      - "443:443"
    volumes:
      - wordpress_data:/var/www/html
    networks:
      - inception
    depends_on:
      - wordpress
    restart: always

  redis:
    container_name: redis
    build: ./requirements/bonus/redis
    image: redis
    networks:
      - inception
    restart: always

secrets:
  db_password:
    file: ../secrets/db_password
  db_root_password:
    file: ../secrets/db_root_password

volumes:
  mariadb_data:
    driver: local
    driver_opts:
      type: none
      device: /home/${USER}/data/mariadb
      o: bind
  wordpress_data:
    driver: local
    driver_opts:
      type: none
      device: /home/${USER}/data/wordpress
      o: bind

networks:
  inception:
    driver: bridge
