version: "3.8"

services:
  mariadb:
    container_name: mariadb
    build:
      context: ./requirements/mariadb
    secrets:
      - db_password
      - db_root_password
    environment:
      MYSQL_DATABASE: ${WORDPRESS_DB_NAME}
      MYSQL_USER: ${WORDPRESS_DB_USER}
      MYSQL_PASSWORD_FILE: /run/secrets/db_password
      MYSQL_ROOT_PASSWORD_FILE: /run/secrets/db_root_password
    volumes:
      - mariadb_data:/var/lib/mysql
    networks:
      - inception
    restart: always

  wordpress:
    container_name: wordpress
    build:
      context: ./requirements/wordpress
    secrets:
      - db_password
      - db_root_password
    environment:
      WORDPRESS_DB_HOST: mariadb
      WORDPRESS_DB_PORT: 3306
      WORDPRESS_DB_NAME: ${WORDPRESS_DB_NAME}
      WORDPRESS_DB_USER: ${WORDPRESS_DB_USER}
      WORDPRESS_ROOT_USER: ${WORDPRESS_ROOT_USER}
      WORDPRESS_DB_PASSWORD_FILE: /run/secrets/db_password
    volumes:
      - wordpress_data:/var/www/html
    networks:
      - inception
    depends_on:
      - mariadb
    restart: always

  nginx:
    container_name: nginx
    build:
      context: ./requirements/nginx
    ports:
      - "443:443"
    volumes:
      - wordpress_data:/var/www/html
    networks:
      - inception
    depends_on:
      - wordpress
    restart: always

secrets:
  db_password:
    file: ../secrets/db_password
  db_root_password:
    file: ../secrets/db_root_password

volumes:
  mariadb_data:
    driver: local
    driver_opts:
      type: none
      device: /Users/mac/data/mariadb
      o: bind
  wordpress_data:
    driver: local
    driver_opts:
      type: none
      device: /Users/mac//data/wordpress
      o: bind

networks:
  inception:
    driver: bridge
